# Generated by Django 2.2.7 on 2019-11-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MYWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_wallet', models.CharField(max_length=70, verbose_name='Nome Carteira')),
                ('var_wallet', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Inicial da Carteira')),
                ('log_create', models.DateTimeField(auto_now=True)),
                ('type_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.TypeWallet', verbose_name='Tipo de Carteira')),
            ],
        ),
    ]
